name: Fetch Match IDs

on:
  workflow_dispatch:       

jobs:
  fetch-match-ids:
    runs-on: ubuntu-latest

    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
      SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
      SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_DB_PORT: ${{ secrets.SUPABASE_DB_PORT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary pandas

      - name: Run match ID extraction
        run: python matchids_extraction.py

      - name: Push CSV to repo
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin main
          git add data/matchids/match_ids_*.csv
          git commit -m "Update match IDs CSV [skip ci]" || echo "No changes to commit"
          git push origin main
